/** 資料庫-原子-城市-列舉 */
export enum DbAtomCityEnum {
  /** 未選擇 */
  NotSelected = -1,
  /** 未定義 */
  Undefined = 0,
  /** 基隆市 */
  Keelung = 1,
  /** 新北市 */
  NewTaipei = 2,
  /** 臺北市 */
  Taipei = 3,
  /** 桃園市 */
  Taoyuan = 4,
  /** 新竹縣 */
  HsinchuCounty = 5,
  /** 新竹市 */
  HsinchuCity = 6,
  /** 苗栗縣 */
  Miaoli = 7,
  /** 臺中市 */
  Taichung = 8,
  /** 彰化縣 */
  Changhua = 9,
  /** 南投縣 */
  Nantou = 10,
  /** 雲林縣 */
  Yunlin = 11,
  /** 嘉義縣 */
  ChiayiCounty = 12,
  /** 嘉義市 */
  ChiayiCity = 13,
  /** 臺南市 */
  Tainan = 14,
  /** 高雄市 */
  Kaohsiung = 15,
  /** 屏東縣 */
  Pingtung = 16,
  /** 臺東縣 */
  Taitung = 17,
  /** 花蓮縣 */
  Hualien = 18,
  /** 宜蘭縣 */
  Yilan = 19,
  /** 澎湖縣 */
  Penghu = 20,
  /** 金門縣 */
  Kinmen = 21,
  /** 連江縣 */
  Lienchiang = 22,
}
