// Auto-generated from organization/orgMember.md
export interface OrgMemberDirectoryItem {
  name: string;
  email: string;
  regionName: string;
  departmentName: string;
}

export const orgMemberDirectory: OrgMemberDirectoryItem[] = [
  {
    name: "巫彥潤",
    email: "stan@bccs.com.tw",
    regionName: "北區",
    departmentName: "工程部",
  },
  {
    name: "黃偉弘",
    email: "wayne@bccs.com.tw",
    regionName: "北區",
    departmentName: "工程部",
  },
  {
    name: "呂紹皇",
    email: "jades@bccs.com.tw",
    regionName: "北區",
    departmentName: "工程部",
  },
  {
    name: "許皓斌",
    email: "michael@bccs.com.tw",
    regionName: "北區",
    departmentName: "工程部",
  },
  {
    name: "黃奇賢",
    email: "david@bccs.com.tw",
    regionName: "北區",
    departmentName: "工程部",
  },
  {
    name: "蘇俊岳",
    email: "chansu@bccs.com.tw",
    regionName: "北區",
    departmentName: "工程部",
  },
  {
    name: "蘇郁昕",
    email: "andy@bccs.com.tw",
    regionName: "北區",
    departmentName: "工程部",
  },
  {
    name: "孫振聲",
    email: "jamsonsun@bccs.com.tw",
    regionName: "北區",
    departmentName: "工程部",
  },
  {
    name: "洪郁淳",
    email: "qunnie@bccs.com.tw",
    regionName: "北區",
    departmentName: "工程部",
  },
  {
    name: "林幸慧",
    email: "bali@bccs.com.tw",
    regionName: "北區",
    departmentName: "工程部",
  },
  {
    name: "李寬",
    email: "neil@bccs.com.tw",
    regionName: "北區",
    departmentName: "工程部",
  },
  {
    name: "王心諭",
    email: "cindy_wang@bccs.com.tw",
    regionName: "北區",
    departmentName: "業務部",
  },
  {
    name: "林育真",
    email: "fion@bccs.com.tw",
    regionName: "北區",
    departmentName: "業務部",
  },
  {
    name: "陳伊莉",
    email: "elizachen@bccs.com.tw",
    regionName: "北區",
    departmentName: "業務部",
  },
  {
    name: "蘇佳秀",
    email: "judy@bccs.com.tw",
    regionName: "北區",
    departmentName: "業務部",
  },
  {
    name: "蘇宥綺",
    email: "charlotte@bccs.com.tw",
    regionName: "北區",
    departmentName: "業務部",
  },
  {
    name: "簡彥庭",
    email: "chad@bccs.com.tw",
    regionName: "北區",
    departmentName: "北區技服部",
  },
  {
    name: "張庭禎",
    email: "jamiechang@bccs.com.tw",
    regionName: "北區",
    departmentName: "北區技服部",
  },
  {
    name: "何旻倫",
    email: "james.he@bccs.com.tw",
    regionName: "北區",
    departmentName: "北區技服部",
  },
  {
    name: "施祥倫",
    email: "aaron.shih@bccs.com.tw",
    regionName: "北區",
    departmentName: "行銷處",
  },
  {
    name: "葉敏嬌",
    email: "angel@bccs.com.tw",
    regionName: "北區",
    departmentName: "協銷部",
  },
  {
    name: "黃依芳",
    email: "evan.huang@bccs.com.tw",
    regionName: "北區",
    departmentName: "協銷部",
  },
  {
    name: "林珮蓁",
    email: "mia@bccs.com.tw",
    regionName: "北區",
    departmentName: "人資行政處",
  },
  {
    name: "張勻漢",
    email: "harry@bccs.com.tw",
    regionName: "北區",
    departmentName: "北區顧問部",
  },
  {
    name: "蔡中維",
    email: "josh@bccs.com.tw",
    regionName: "北區",
    departmentName: "北區顧問部",
  },
  {
    name: "方沛",
    email: "pei@bccs.com.tw",
    regionName: "北區",
    departmentName: "北區顧問部",
  },
  {
    name: "黃丹茵",
    email: "diane@bccs.com.tw",
    regionName: "北區",
    departmentName: "北區顧問部",
  },
  {
    name: "楊禔昇",
    email: "kandle@bccs.com.tw",
    regionName: "北區",
    departmentName: "北區顧問部",
  },
  {
    name: "鄭穎華",
    email: "allison@bccs.com.tw",
    regionName: "北區",
    departmentName: "北區顧問部",
  },
  {
    name: "詹美玲",
    email: "jasmine@bccs.com.tw",
    regionName: "北區",
    departmentName: "北區顧問部",
  },
  {
    name: "陳建良",
    email: "allenc@bccs.com.tw",
    regionName: "中區",
    departmentName: "總經理",
  },
  {
    name: "許碧薰",
    email: "fanny@bccs.com.tw",
    regionName: "中區",
    departmentName: "財務處",
  },
  {
    name: "馬燕芬",
    email: "magrlet@bccs.com.tw",
    regionName: "中區",
    departmentName: "財務處",
  },
  {
    name: "鄭芳俞",
    email: "hermit@bccs.com.tw",
    regionName: "中區",
    departmentName: "人資行政處",
  },
  {
    name: "林幸瑜",
    email: "anita@bccs.com.tw",
    regionName: "中區",
    departmentName: "人資行政處",
  },
  {
    name: "廖育慧",
    email: "mobby@bccs.com.tw",
    regionName: "中區",
    departmentName: "人資行政處",
  },
  {
    name: "黃怡菁",
    email: "noguchi@bccs.com.tw",
    regionName: "中區",
    departmentName: "人資行政處",
  },
  {
    name: "覺煒翔",
    email: "coin@bccs.com.tw",
    regionName: "中區",
    departmentName: "業務部",
  },
  {
    name: "謝心怡",
    email: "ann@bccs.com.tw",
    regionName: "中區",
    departmentName: "業務部",
  },
  {
    name: "張敏瑜",
    email: "mandy@bccs.com.tw",
    regionName: "中區",
    departmentName: "業務部",
  },
  {
    name: "藍士益",
    email: "york@bccs.com.tw",
    regionName: "中區",
    departmentName: "工程部",
  },
  {
    name: "顏弦禾",
    email: "allen_yen@bccs.com.tw",
    regionName: "中區",
    departmentName: "工程部",
  },
  {
    name: "廖桂依",
    email: "green@bccs.com.tw",
    regionName: "中區",
    departmentName: "工程部",
  },
  {
    name: "江俊宇",
    email: "junyu@bccs.com.tw",
    regionName: "中區",
    departmentName: "工程部",
  },
  {
    name: "王莠棋",
    email: "youqi@bccs.com.tw",
    regionName: "中區",
    departmentName: "工程部",
  },
  {
    name: "李承洹",
    email: "claire_lee@bccs.com.tw",
    regionName: "中區",
    departmentName: "工程部",
  },
  {
    name: "謝映真",
    email: "ava@bccs.com.tw",
    regionName: "中區",
    departmentName: "中區技服部",
  },
  {
    name: "張荃",
    email: "egan@bccs.com.tw",
    regionName: "中區",
    departmentName: "中區技服部",
  },
  {
    name: "廖梓善",
    email: "johnliao@bccs.com.tw",
    regionName: "中區",
    departmentName: "中區技服部",
  },
  {
    name: "謝易男",
    email: "alan@bccs.com.tw",
    regionName: "中區",
    departmentName: "系統維護部",
  },
  {
    name: "莊清斌",
    email: "simon@bccs.com.tw",
    regionName: "中區",
    departmentName: "系統維護部",
  },
  {
    name: "李子涵",
    email: "isaac_lee@bccs.com.tw",
    regionName: "中區",
    departmentName: "協銷部",
  },
  {
    name: "陳勁宇",
    email: "thomas@bccs.com.tw",
    regionName: "中區",
    departmentName: "協銷部",
  },
  {
    name: "王緯宇",
    email: "davidwang@bccs.com.tw",
    regionName: "中區",
    departmentName: "專案部",
  },
  {
    name: "韓連恩",
    email: "louise-han@bccs.com.tw",
    regionName: "中區",
    departmentName: "企劃部",
  },
  {
    name: "陳暐曜",
    email: "weiyao@bccs.com.tw",
    regionName: "中區",
    departmentName: "研發部",
  },
  {
    name: "陳佳沛",
    email: "claire@bccs.com.tw",
    regionName: "中區",
    departmentName: "研發部",
  },
  {
    name: "徐妤涵",
    email: "yuhan@bccs.com.tw",
    regionName: "中區",
    departmentName: "研發部",
  },
  {
    name: "劉家銘",
    email: "charming@bccs.com.tw",
    regionName: "中區",
    departmentName: "研發部",
  },
  {
    name: "莊仕偉",
    email: "chuangbahen@bccs.com.tw",
    regionName: "中區",
    departmentName: "研發部",
  },
  {
    name: "吳聲強",
    email: "ivan@bccs.com.tw",
    regionName: "中區",
    departmentName: "研發部",
  },
  {
    name: "顏瑞慶",
    email: "ray@bccs.com.tw",
    regionName: "中區",
    departmentName: "監控部",
  },
  {
    name: "王聖博",
    email: "sam@bccs.com.tw",
    regionName: "中區",
    departmentName: "監控部",
  },
  {
    name: "徐佑誠",
    email: "richard@bccs.com.tw",
    regionName: "中區",
    departmentName: "監控部",
  },
  {
    name: "陳建安",
    email: "john@bccs.com.tw",
    regionName: "中區",
    departmentName: "監控部",
  },
  {
    name: "呂柏薰",
    email: "jsnn@bccs.com.tw",
    regionName: "中區",
    departmentName: "AI 智能部",
  },
  {
    name: "戴慈葦",
    email: "wiwi@bccs.com.tw",
    regionName: "中區",
    departmentName: "AI 智能部",
  },
  {
    name: "巫若瑋",
    email: "ren.wu@bccs.com.tw",
    regionName: "中區",
    departmentName: "策略執行部",
  },
  {
    name: "陳佳偉",
    email: "bruce@bccs.com.tw",
    regionName: "中區",
    departmentName: "中區顧問部",
  },
  {
    name: "林沛鑑",
    email: "aaron@bccs.com.tw",
    regionName: "中區",
    departmentName: "中區顧問部",
  },
  {
    name: "陳泰龍",
    email: "felix@bccs.com.tw",
    regionName: "中區",
    departmentName: "中區顧問部",
  },
  {
    name: "李郁倫",
    email: "steven@bccs.com.tw",
    regionName: "中區",
    departmentName: "中區顧問部",
  },
  {
    name: "邱聖茹",
    email: "nunu@bccs.com.tw",
    regionName: "中區",
    departmentName: "中區顧問部",
  },
  {
    name: "黃國維",
    email: "ryanhuang@bccs.com.tw",
    regionName: "中區",
    departmentName: "中區顧問部",
  },
  {
    name: "鄭以昇",
    email: "eason@bccs.com.tw",
    regionName: "中區",
    departmentName: "中區顧問部",
  },
  {
    name: "尤秋評",
    email: "eileen@bccs.com.tw",
    regionName: "中區",
    departmentName: "中區顧問部",
  },
  {
    name: "梁秋玲",
    email: "aling@bccs.com.tw",
    regionName: "中區",
    departmentName: "中區顧問部",
  },
  {
    name: "魏華廷",
    email: "otto@bccs.com.tw",
    regionName: "中區",
    departmentName: "中區顧問部",
  },
  {
    name: "黃昱誌",
    email: "huangyz@bccs.com.tw",
    regionName: "南區",
    departmentName: "南區技服部",
  },
  {
    name: "呂瑋原",
    email: "eric@bccs.com.tw",
    regionName: "南區",
    departmentName: "管理顧問處",
  },
  {
    name: "劉書瑜",
    email: "rizzy@bccs.com.tw",
    regionName: "南區",
    departmentName: "南區顧問部",
  },
  {
    name: "盧彥伶",
    email: "ellie@bccs.com.tw",
    regionName: "南區",
    departmentName: "協銷部",
  },
  {
    name: "陳品威",
    email: "dylan@bccs.com.tw",
    regionName: "南區",
    departmentName: "系統開發部",
  },
  {
    name: "葉育岑",
    email: "julie@bccs.com.tw",
    regionName: "南區",
    departmentName: "人資行政處",
  },
  {
    name: "孫加榮",
    email: "riley@bccs.com.tw",
    regionName: "南區",
    departmentName: "南區顧問部",
  },
  {
    name: "楊雯珺",
    email: "janice@bccs.com.tw",
    regionName: "南區",
    departmentName: "南區顧問部",
  },
  {
    name: "胡瑞賢",
    email: "ray.hu@bccs.com.tw",
    regionName: "南區",
    departmentName: "南區顧問部",
  },
  {
    name: "郭家瑋",
    email: "david.kuo@bccs.com.tw",
    regionName: "南區",
    departmentName: "南區顧問部",
  },
  {
    name: "左寧生",
    email: "ningsheng@bccs.com.tw",
    regionName: "南區",
    departmentName: "南區顧問部",
  },
  {
    name: "何冠龍",
    email: "ted@bccs.com.tw",
    regionName: "南區",
    departmentName: "南區顧問部",
  },
  {
    name: "陳俊茂",
    email: "charles@bccs.com.tw",
    regionName: "南區",
    departmentName: "南區顧問部",
  },
  {
    name: "郭毓雯",
    email: "rhine@bccs.com.tw",
    regionName: "南區",
    departmentName: "南區顧問部",
  },
  {
    name: "張家華",
    email: "rex.chang@bccs.com.tw",
    regionName: "南區",
    departmentName: "南區顧問部",
  },
  {
    name: "林佳璟",
    email: "lisa@bccs.com.tw",
    regionName: "南區",
    departmentName: "業務部",
  },
  {
    name: "林佳蓓",
    email: "mita@bccs.com.tw",
    regionName: "南區",
    departmentName: "業務部",
  },
  {
    name: "駱姵辰",
    email: "karen@bccs.com.tw",
    regionName: "南區",
    departmentName: "業務部",
  },
  {
    name: "劉富銓",
    email: "mars@bccs.com.tw",
    regionName: "南區",
    departmentName: "工程部",
  },
  {
    name: "陳一雯",
    email: "wendy@bccs.com.tw",
    regionName: "南區",
    departmentName: "工程部",
  },
  {
    name: "陳嘉聯",
    email: "daniel@bccs.com.tw",
    regionName: "南區",
    departmentName: "工程部",
  },
  {
    name: "郭欲慎",
    email: "yushen@bccs.com.tw",
    regionName: "南區",
    departmentName: "工程部",
  },
  {
    name: "邱鈺淋",
    email: "linda@bccs.com.tw",
    regionName: "南區",
    departmentName: "工程部",
  },
  {
    name: "林澄璋",
    email: "stray@bccs.com.tw",
    regionName: "南區",
    departmentName: "工程部",
  },
  {
    name: "賴奕丞",
    email: "ericlai@bccs.com.tw",
    regionName: "南區",
    departmentName: "南區技服部",
  },
  {
    name: "黃淑琦",
    email: "ellen@bccs.com.tw",
    regionName: "南區",
    departmentName: "人資行政處",
  },
  {
    name: "呂耀中",
    email: "leonlu@bccs.com.tw",
    regionName: "南區",
    departmentName: "安全實驗室",
  },
  {
    name: "黃沛瑜",
    email: "olliehuang@bccs.com.tw",
    regionName: "南區",
    departmentName: "安全實驗室",
  },
  {
    name: "吳孟珊",
    email: "vivianwu@bccs.com.tw",
    regionName: "南區",
    departmentName: "安全實驗室",
  },
  {
    name: "謝曉柔",
    email: "aria@bccs.com.tw",
    regionName: "南區",
    departmentName: "系統開發部",
  },
];
