export const mockDataSets = {
  employees: [
    {
      EmployeeID: "EMP001",
      EmployeeAccount: "admin",
      EmployeeName: "系統管理員",
      EmployeeEmail: "admin@company.com",
      DepartmentID: "DEPT001",
      DepartmentName: "資訊部",
      RoleID: "ROLE001",
      RoleName: "系統管理員",
      IsEnable: true,
      CreateTime: "2024-01-01T00:00:00",
    },
    {
      EmployeeID: "EMP002",
      EmployeeAccount: "john.doe",
      EmployeeName: "約翰",
      EmployeeEmail: "john@company.com",
      DepartmentID: "DEPT002",
      DepartmentName: "研發部",
      RoleID: "ROLE002",
      RoleName: "專案經理",
      IsEnable: true,
      CreateTime: "2024-01-15T00:00:00",
    },
    {
      EmployeeID: "EMP003",
      EmployeeAccount: "jane.smith",
      EmployeeName: "珍妮",
      EmployeeEmail: "jane@company.com",
      DepartmentID: "DEPT002",
      DepartmentName: "研發部",
      RoleID: "ROLE003",
      RoleName: "工程師",
      IsEnable: true,
      CreateTime: "2024-02-01T00:00:00",
    },
  ],

  companies: [
    {
      CompanyID: "CMP001",
      CompanyName: "科技創新股份有限公司",
      CompanyUniformNumber: "12345678",
      CompanyPhone: "02-12345678",
      CompanyFax: "02-12345679",
      CompanyAddress: "台北市信義區信義路五段7號",
      CompanyEmail: "contact@techinnov.com",
      ContactPersonName: "王經理",
      ContactPersonPhone: "0912-345-678",
      IsEnable: true,
      CreateTime: "2024-01-10T00:00:00",
    },
    {
      CompanyID: "CMP002",
      CompanyName: "數位轉型企業有限公司",
      CompanyUniformNumber: "23456789",
      CompanyPhone: "04-23456789",
      CompanyFax: "04-23456780",
      CompanyAddress: "台中市西屯區台灣大道三段99號",
      CompanyEmail: "info@digitaltrans.com",
      ContactPersonName: "李總監",
      ContactPersonPhone: "0922-456-789",
      IsEnable: true,
      CreateTime: "2024-01-20T00:00:00",
    },
  ],

  crmPipelines: [
    {
      id: 1,
      status: 2,
      companyName: "台積電",
      contacterDepartment: "資訊部",
      contacterJobTitle: "經理",
      contacterName: "王小明",
      contacterEmail: "xiaoming@tsmc.com",
      contacterPhone: "0912-345-678",
      contacterTelephone: "02-1234-5678",
      salerEmployeeName: "林家豪",
    },
    {
      id: 2,
      status: 3,
      companyName: "聯發科",
      contacterDepartment: "採購部",
      contacterJobTitle: "副理",
      contacterName: "李雅婷",
      contacterEmail: "yating@mediatek.com",
      contacterPhone: "0922-456-789",
      contacterTelephone: "02-2345-6789",
      salerEmployeeName: "陳志強",
    },
    {
      id: 3,
      status: 4,
      companyName: "鴻海科技",
      contacterDepartment: "業務部",
      contacterJobTitle: "主任",
      contacterName: "張文彥",
      contacterEmail: "wenyan@foxconn.com",
      contacterPhone: "0933-567-890",
      contacterTelephone: "02-3456-7890",
      salerEmployeeName: "周雅婷",
    },
    {
      id: 4,
      status: 5,
      companyName: "廣達電腦",
      contacterDepartment: "研發部",
      contacterJobTitle: "協理",
      contacterName: "陳美玲",
      contacterEmail: "meiling@quantam.com",
      contacterPhone: "0955-111-222",
      contacterTelephone: "02-4567-8901",
      salerEmployeeName: "黃俊傑",
    },
    {
      id: 5,
      status: 7,
      companyName: "華碩電腦",
      contacterDepartment: "行銷部",
      contacterJobTitle: "總監",
      contacterName: "吳建國",
      contacterEmail: "jianguo@asus.com",
      contacterPhone: "0966-222-333",
      contacterTelephone: "02-5678-9012",
      salerEmployeeName: "徐婉如",
    },
    {
      id: 6,
      status: 8,
      companyName: "仁寶電腦",
      contacterDepartment: "資訊部",
      contacterJobTitle: "專員",
      contacterName: "周大華",
      contacterEmail: "dahua@compal.com",
      contacterPhone: "0977-333-444",
      contacterTelephone: "02-6789-0123",
      salerEmployeeName: "張志強",
    },
    {
      id: 7,
      status: 9,
      companyName: "台灣大哥大",
      contacterDepartment: "總經理室",
      contacterJobTitle: "顧問",
      contacterName: "黃俊傑",
      contacterEmail: "junjie@twm.com",
      contacterPhone: "0988-444-555",
      contacterTelephone: "02-7890-1234",
      salerEmployeeName: "王小明",
    },
    {
      id: 8,
      status: 10,
      companyName: "中華電信",
      contacterDepartment: "財務部",
      contacterJobTitle: "主任",
      contacterName: "林淑芬",
      contacterEmail: "shufen@cht.com",
      contacterPhone: "0999-555-666",
      contacterTelephone: "02-8901-2345",
      salerEmployeeName: "李雅婷",
    },
    {
      id: 9,
      status: 11,
      companyName: "國泰金控",
      contacterDepartment: "人資部",
      contacterJobTitle: "經理",
      contacterName: "吳婉如",
      contacterEmail: "wanru@cathay.com",
      contacterPhone: "0911-666-777",
      contacterTelephone: "02-9012-3456",
      salerEmployeeName: "陳美玲",
    },
    {
      id: 10,
      status: 12,
      companyName: "富邦金控",
      contacterDepartment: "資訊部",
      contacterJobTitle: "副理",
      contacterName: "徐文彥",
      contacterEmail: "wenyan@fubon.com",
      contacterPhone: "0922-777-888",
      contacterTelephone: "02-0123-4567",
      salerEmployeeName: "周大華",
    },
  ],

  projects: [
    {
      ProjectID: "PRJ001",
      ProjectName: "內部系統重構專案",
      ProjectCode: "PROJ-2024-001",
      CompanyID: "CMP001",
      CompanyName: "科技創新股份有限公司",
      ProjectManagerID: "EMP002",
      ProjectManagerName: "約翰",
      StartDate: "2024-01-01",
      EndDate: "2024-12-31",
      ProjectStatus: "進行中",
      BudgetAmount: 8000000,
      ActualAmount: 3500000,
      CompletionPercent: 45,
    },
  ],
  workProjects: [
    {
      id: 1,
      status: 3,
      name: "S004-顧問諮詢-預設產品",
      companyName: "漢昕科技股份有限公司",
      departmentName: "顧問部",
      regionId: 2,
      grossProfit: 2100000,
      serviceItemNames: ["顧問諮詢"],
      startTime: "2026-01-13",
      endTime: "2026-01-31",
      isRenewal: false,
      isOutsourced: false,
    },
    {
      id: 2,
      status: 2,
      name: "S003-風險檢測-預設產品",
      companyName: "哈利公司-update",
      departmentName: "工程部",
      regionId: 1,
      grossProfit: 1800000,
      serviceItemNames: ["風險檢測"],
      startTime: "2026-01-10",
      endTime: "2026-01-31",
      isRenewal: true,
      isOutsourced: false,
    },
    {
      id: 3,
      status: 4,
      name: "H013-雲安維運-EDR",
      companyName: "漢昕科技股份有限公司",
      departmentName: "工程部",
      regionId: 2,
      grossProfit: 2400000,
      serviceItemNames: ["雲安維運"],
      startTime: "2026-01-01",
      endTime: "2026-01-31",
      isRenewal: true,
      isOutsourced: false,
    },
    {
      id: 4,
      status: 2,
      name: "聯防設備+資安學苑-預設產品+預設產品",
      companyName: "哈利公司-update",
      departmentName: "策略執行部",
      regionId: 1,
      grossProfit: 1500000,
      serviceItemNames: ["聯防設備", "資安學苑"],
      startTime: "2026-01-01",
      endTime: "2026-01-23",
      isRenewal: false,
      isOutsourced: false,
    },
    {
      id: 5,
      status: 5,
      name: "雲安維運-EDR",
      companyName: "哈利公司-update",
      departmentName: "工程部",
      regionId: 1,
      grossProfit: 2000000,
      serviceItemNames: ["雲安維運"],
      startTime: "2026-01-10",
      endTime: "2026-01-31",
      isRenewal: false,
      isOutsourced: false,
    },
    {
      id: 6,
      status: 3,
      name: "雲安維運-EDR",
      companyName: "王品有限公司",
      departmentName: "工程部",
      regionId: 3,
      grossProfit: 2800000,
      serviceItemNames: ["雲安維運"],
      startTime: "2026-01-01",
      endTime: "2026-01-31",
      isRenewal: false,
      isOutsourced: false,
    },
  ],

  departments: [
    {
      DepartmentID: "DEPT001",
      DepartmentName: "資訊部",
      DepartmentCode: "IT",
      ParentDepartmentID: null,
      ParentDepartmentName: null,
      ManagerEmployeeID: "EMP001",
      ManagerEmployeeName: "系統管理員",
      IsEnable: true,
    },
    {
      DepartmentID: "DEPT002",
      DepartmentName: "研發部",
      DepartmentCode: "RD",
      ParentDepartmentID: null,
      ParentDepartmentName: null,
      ManagerEmployeeID: "EMP002",
      ManagerEmployeeName: "約翰",
      IsEnable: true,
    },
  ],

  roles: [
    {
      RoleID: "ROLE001",
      RoleName: "系統管理員",
      RoleCode: "ADMIN",
      RoleDescription: "系統最高權限管理員",
      IsEnable: true,
    },
    {
      RoleID: "ROLE002",
      RoleName: "專案經理",
      RoleCode: "PM",
      RoleDescription: "專案管理與執行",
      IsEnable: true,
    },
    {
      RoleID: "ROLE003",
      RoleName: "工程師",
      RoleCode: "ENG",
      RoleDescription: "技術開發人員",
      IsEnable: true,
    },
  ],

  crmActivities: [
    {
      id: 1,
      name: "2026 春季資安論壇",
      kind: 1,
      startTime: "2026-03-15T09:00:00",
      endTime: "2026-03-15T17:00:00",
      location: "台北國際會議中心",
      expectedLeadCount: 120,
      registeredCount: 85,
      transferredToSalesCount: 20,
      sponsorTotal: 350000,
      expenseTotal: 180000,
      opportunityCount: 6,
      content: "聚焦資安策略與實務案例分享，邀請多家企業講者。",
    },
    {
      id: 2,
      name: "雲端遷移線上研討會",
      kind: 2,
      startTime: "2026-04-10T14:00:00",
      endTime: "2026-04-10T16:30:00",
      location: "Microsoft Teams",
      expectedLeadCount: 200,
      registeredCount: 160,
      transferredToSalesCount: 30,
      sponsorTotal: 120000,
      expenseTotal: 40000,
      opportunityCount: 9,
      content: "介紹雲端架構設計與遷移最佳實務。",
    },
    {
      id: 3,
      name: "智慧製造體驗日",
      kind: 1,
      startTime: "2026-05-02T10:00:00",
      endTime: "2026-05-02T16:00:00",
      location: "台中創新園區",
      expectedLeadCount: 90,
      registeredCount: 70,
      transferredToSalesCount: 15,
      sponsorTotal: 90000,
      expenseTotal: 50000,
      opportunityCount: 4,
      content: "展示智慧製造方案與即時產線監控。",
    },
    {
      id: 4,
      name: "AI 應用高峰會",
      kind: 1,
      startTime: "2026-06-01T09:30:00",
      endTime: "2026-06-01T18:00:00",
      location: "高雄展覽館",
      expectedLeadCount: 160,
      registeredCount: 110,
      transferredToSalesCount: 28,
      sponsorTotal: 500000,
      expenseTotal: 260000,
      opportunityCount: 11,
      content: "探討 AI 在製造、金融、醫療的落地案例。",
    },
    {
      id: 5,
      name: "資安教育訓練工作坊",
      kind: 2,
      startTime: "2026-06-18T13:00:00",
      endTime: "2026-06-18T17:30:00",
      location: "Zoom 線上會議室",
      expectedLeadCount: 80,
      registeredCount: 60,
      transferredToSalesCount: 10,
      sponsorTotal: 30000,
      expenseTotal: 15000,
      opportunityCount: 3,
      content: "資安教育訓練與演練實作。",
    },
    {
      id: 6,
      name: "2026 金融科技論壇",
      kind: 1,
      startTime: "2026-07-08T09:00:00",
      endTime: "2026-07-08T17:00:00",
      location: "台北南港展覽館",
      expectedLeadCount: 140,
      registeredCount: 96,
      transferredToSalesCount: 24,
      sponsorTotal: 280000,
      expenseTotal: 160000,
      opportunityCount: 7,
      content: "金融科技解決方案展示與交流。",
    },
    {
      id: 7,
      name: "企業資料治理說明會",
      kind: 2,
      startTime: "2026-08-05T10:30:00",
      endTime: "2026-08-05T12:00:00",
      location: "Google Meet",
      expectedLeadCount: 60,
      registeredCount: 45,
      transferredToSalesCount: 8,
      sponsorTotal: 20000,
      expenseTotal: 8000,
      opportunityCount: 2,
      content: "資料治理與主數據管理方案分享。",
    },
    {
      id: 8,
      name: "ESG 數位轉型研討會",
      kind: 1,
      startTime: "2026-09-12T09:00:00",
      endTime: "2026-09-12T16:00:00",
      location: "新竹科學園區",
      expectedLeadCount: 100,
      registeredCount: 78,
      transferredToSalesCount: 19,
      sponsorTotal: 150000,
      expenseTotal: 90000,
      opportunityCount: 5,
      content: "ESG 數位化落地與系統整合案例。",
    },
    {
      id: 9,
      name: "製造業 IoT 解決方案日",
      kind: 1,
      startTime: "2026-10-03T10:00:00",
      endTime: "2026-10-03T17:00:00",
      location: "台南文化中心",
      expectedLeadCount: 110,
      registeredCount: 88,
      transferredToSalesCount: 22,
      sponsorTotal: 130000,
      expenseTotal: 70000,
      opportunityCount: 6,
      content: "展示 IoT 感測與設備管理方案。",
    },
    {
      id: 10,
      name: "年度產品發表會",
      kind: 1,
      startTime: "2026-11-20T13:00:00",
      endTime: "2026-11-20T17:00:00",
      location: "台北世貿中心",
      expectedLeadCount: 220,
      registeredCount: 170,
      transferredToSalesCount: 40,
      sponsorTotal: 600000,
      expenseTotal: 320000,
      opportunityCount: 14,
      content: "年度新品發表與功能展示。",
    },
  ],
  teleSalesLeads: [
    {
      id: 1,
      companyName: "星光資訊股份有限公司",
      industry: "資訊服務",
      source: "活動管理",
      contactName: "王小明",
      value: "中價值",
      status: "待聯繫",
    },
    {
      id: 5,
      companyName: "綠能科技有限公司",
      industry: "能源",
      source: "電銷自建",
      contactName: "吳建國",
      value: "低價值",
      status: "待聯繫",
    },
    {
      id: 10,
      companyName: "新創雲端服務",
      industry: "雲端服務",
      source: "電銷自建",
      contactName: "周大華",
      value: "高價值",
      status: "待聯繫",
    },
    {
      id: 2,
      companyName: "宏達系統科技",
      industry: "製造業",
      source: "電銷自建",
      contactName: "李雅婷",
      value: "高價值",
      status: "已聯繫",
    },
    {
      id: 6,
      companyName: "創新醫療科技",
      industry: "醫療",
      source: "活動管理",
      contactName: "周婉如",
      value: "中價值",
      status: "已聯繫",
    },
    {
      id: 3,
      companyName: "遠景行銷顧問",
      industry: "行銷顧問",
      source: "活動管理",
      contactName: "張志強",
      value: "中價值",
      status: "已約訪",
    },
    {
      id: 7,
      companyName: "超點物流股份有限公司",
      industry: "物流",
      source: "批次匯入",
      contactName: "徐文彥",
      value: "待評估",
      status: "已約訪",
    },
    {
      id: 4,
      companyName: "智匯金融顧問",
      industry: "金融服務",
      source: "批次匯入",
      contactName: "陳美玲",
      value: "高價值",
      status: "已派送",
    },
    {
      id: 8,
      companyName: "翔宇教育科技",
      industry: "教育",
      source: "電銷自建",
      contactName: "林淑芬",
      value: "中價值",
      status: "已派送",
    },
    {
      id: 9,
      companyName: "宏景資安顧問",
      industry: "資安顧問",
      source: "活動管理",
      contactName: "黃俊傑",
      value: "低價值",
      status: "不再聯繫",
    },
  ],

  teleSalesRecords: [
    {
      id: 1,
      activityId: 1,
      activityName: "4 月 T5 展攤_iThome 資安展",
      activityKind: "實體活動",
      activityDate: "2025-04-17",
      teleSalesRep: "Evan",
      callTimeRange: "12/25-12/31",
      industry: "一般企業、自動控制相關業",
      evaluationRange: "非編列預算制度，採需求評估",
      discussItem: "EDR MDR 產品+公司服務",
      interestLevel: "直接商機-邀約成功到場產品+公司服務介紹",
      note: "主要窗口",
      listStatus: "已轉業務",
      assignedSales: "Lisa",
      discussNote:
        "12/30 寄公司服務&_BCCS MDR EDM。非編列預算制度，採需求評估，在明年計畫有評估 EDR 或 MDR，邀約產品+公司服務介紹成功。客戶可以的時間 1 月份都可以。",
      companyName: "中和碁電股份有限公司",
      contactName: "陳信溢",
      contactDepartment: "管理部",
      contactTitle: "資訊工程",
      contactEmail: "ponisoon@jidien.com",
      companyPhone: "06-266-8899#504",
      mobilePhone: "",
      contactAddress: "台南",
      customerData1: "",
      customerData2: "",
      customerData3: "",
      customerData4: "",
    },
    {
      id: 2,
      activityId: 1,
      activityName: "4 月 T5 展攤_iThome 資安展",
      activityKind: "實體活動",
      activityDate: "2025-04-17",
      teleSalesRep: "Evan",
      callTimeRange: "12/25-12/31",
      industry: "一般企業、自行車及其零件製造業",
      evaluationRange: "無資料",
      discussItem: "公司服務",
      interestLevel: "潛在商機_邀約介紹未直接答應表示要內部考慮",
      note: "新增主要窗口",
      listStatus: "已轉業務",
      assignedSales: "Mandy",
      discussNote:
        "新增窗口 12/30 寄公司服務&_BCCS MDR EDM。請先寄資料來參考，表示未來會擴充資安架構。邀約公司服務介紹表示先看資料。",
      companyName: "久鼎金屬實業股份有限公司",
      contactName: "黃先生",
      contactDepartment: "資訊部",
      contactTitle: "",
      contactEmail: "fish.huang@jdco.com.tw",
      companyPhone: "04-22519325#121",
      mobilePhone: "",
      contactAddress: "彰化",
      customerData1: "",
      customerData2: "",
      customerData3: "",
      customerData4: "",
    },
    {
      id: 3,
      activityId: 1,
      activityName: "4 月 T5 展攤_iThome 資安展",
      activityKind: "實體活動",
      activityDate: "2025-04-17",
      teleSalesRep: "Evan",
      callTimeRange: "12/25-12/31",
      industry: "一般企業、工具製造業",
      evaluationRange: "無資料",
      discussItem: "EDR MDR+ISMS",
      interestLevel: "客戶深耕",
      note: "主要窗口",
      listStatus: "已轉業務",
      assignedSales: "Ann",
      discussNote:
        "1/2 客戶回信。由於本年度透過導入 ISO 27001 進行初期風險盤點，短期內暫無需求，後續若有風險專案再評估。",
      companyName: "台中精機廠股份有限公司",
      contactName: "蔣坤樟",
      contactDepartment: "資訊課",
      contactTitle: "資安負責系統工程師",
      contactEmail: "rock@mail.or.com.tw",
      companyPhone: "04-2359-2101#1720",
      mobilePhone: "938562623",
      contactAddress: "408 台中市南屯區精科中二路 1 號",
      customerData1: "台中",
      customerData2: "",
      customerData3: "",
      customerData4: "",
    },
    {
      id: 4,
      activityId: 1,
      activityName: "4 月 T5 展攤_iThome 資安展",
      activityKind: "實體活動",
      activityDate: "2025-04-17",
      teleSalesRep: "Evan",
      callTimeRange: "12/25-12/31",
      industry: "一般企業、工具製造業",
      evaluationRange: "無資料",
      discussItem: "EDR MDR+ISMS",
      interestLevel: "客戶深耕",
      note: "新增次要窗口",
      listStatus: "已轉業務",
      assignedSales: "Ann",
      discussNote:
        "有評估 EDR/MDR，ISO 27001 2022 已找廠商導入，弱掃委外，邀約後續到場簡報 ISO 顧問 + EDR/MDR。",
      companyName: "台中精機廠股份有限公司",
      contactName: "林毓澤",
      contactDepartment: "資訊課",
      contactTitle: "",
      contactEmail: "m4977@mail.or.com.tw",
      companyPhone: "04-2359-2101#1721",
      mobilePhone: "",
      contactAddress: "台中",
      customerData1: "",
      customerData2: "",
      customerData3: "",
      customerData4: "",
    },
    {
      id: 5,
      activityId: 1,
      activityName: "4 月 T5 展攤_iThome 資安展",
      activityKind: "實體活動",
      activityDate: "2025-04-17",
      teleSalesRep: "Evan",
      callTimeRange: "12/25-12/31",
      industry: "上市櫃、馬達／力矩馬達／驅動器及控制器製造業",
      evaluationRange: "無資料",
      discussItem: "公司服務",
      interestLevel: "潛在商機_邀約介紹未直接答應表示要內部考慮",
      note: "主要窗口",
      listStatus: "已轉業務",
      assignedSales: "Ann",
      discussNote:
        "12/30 寄公司服務&_BCCS MDR EDM。會議中確認課長為資安評估主要窗口。",
      companyName: "大銀微系統股份有限公司",
      contactName: "劉華正",
      contactDepartment: "資訊部",
      contactTitle: "課長",
      contactEmail: "howard@hiwinmikro.tw",
      companyPhone: "04-23550110#9181",
      mobilePhone: "",
      contactAddress: "40852 台中市南屯區精科中路 6 號",
      customerData1: "4576",
      customerData2: "上市電機機械",
      customerData3: "精密運動及控制元件之研發製造銷售",
      customerData4: "",
    },
    {
      id: 6,
      activityId: 2,
      activityName: "雲端遷移線上研討會",
      activityKind: "線上活動",
      activityDate: "2026-04-10",
      teleSalesRep: "Evan",
      callTimeRange: "",
      industry: "",
      evaluationRange: "",
      discussItem: "",
      interestLevel: "",
      note: "",
      listStatus: "未撥打",
      assignedSales: "",
      assignedRegion: "",
      discussNote: "",
      companyName: "云圖科技股份有限公司",
      contactName: "王怡君",
      contactDepartment: "資訊部",
      contactTitle: "經理",
      contactEmail: "yijun.wang@cloudmap.tw",
      companyPhone: "02-2788-9000",
      mobilePhone: "",
      contactAddress: "台北市內湖區瑞光路 88 號",
      customerData1: "",
      customerData2: "",
      customerData3: "",
      customerData4: "",
    },
    {
      id: 7,
      activityId: 2,
      activityName: "雲端遷移線上研討會",
      activityKind: "線上活動",
      activityDate: "2026-04-10",
      teleSalesRep: "Evan",
      callTimeRange: "",
      industry: "",
      evaluationRange: "",
      discussItem: "",
      interestLevel: "",
      note: "",
      listStatus: "未撥打",
      assignedSales: "",
      assignedRegion: "",
      discussNote: "",
      companyName: "啟雲資訊股份有限公司",
      contactName: "陳冠宇",
      contactDepartment: "雲端服務部",
      contactTitle: "主任",
      contactEmail: "guanyu.chen@qicloud.com.tw",
      companyPhone: "04-2255-1122",
      mobilePhone: "",
      contactAddress: "台中市西屯區市政北二路 100 號",
      customerData1: "",
      customerData2: "",
      customerData3: "",
      customerData4: "",
    },
    {
      id: 8,
      activityId: 2,
      activityName: "雲端遷移線上研討會",
      activityKind: "線上活動",
      activityDate: "2026-04-10",
      teleSalesRep: "Evan",
      callTimeRange: "",
      industry: "",
      evaluationRange: "",
      discussItem: "",
      interestLevel: "",
      note: "",
      listStatus: "未撥打",
      assignedSales: "",
      assignedRegion: "",
      discussNote: "",
      companyName: "遠景數位整合股份有限公司",
      contactName: "林信宏",
      contactDepartment: "研發部",
      contactTitle: "資深工程師",
      contactEmail: "xinhong.lin@orizon.com.tw",
      companyPhone: "03-550-3311",
      mobilePhone: "",
      contactAddress: "新竹市東區光復路 88 號",
      customerData1: "",
      customerData2: "",
      customerData3: "",
      customerData4: "",
    },
    {
      id: 9,
      activityId: 2,
      activityName: "雲端遷移線上研討會",
      activityKind: "線上活動",
      activityDate: "2026-04-10",
      teleSalesRep: "Evan",
      callTimeRange: "",
      industry: "",
      evaluationRange: "",
      discussItem: "",
      interestLevel: "",
      note: "",
      listStatus: "未撥打",
      assignedSales: "",
      assignedRegion: "",
      discussNote: "",
      companyName: "雲橋金融科技股份有限公司",
      contactName: "黃詩雅",
      contactDepartment: "風控部",
      contactTitle: "副理",
      contactEmail: "shiya.huang@cloudbridge.com",
      companyPhone: "07-338-7766",
      mobilePhone: "",
      contactAddress: "高雄市前鎮區新光路 66 號",
      customerData1: "",
      customerData2: "",
      customerData3: "",
      customerData4: "",
    },
    {
      id: 10,
      activityId: 2,
      activityName: "雲端遷移線上研討會",
      activityKind: "線上活動",
      activityDate: "2026-04-10",
      teleSalesRep: "Evan",
      callTimeRange: "",
      industry: "",
      evaluationRange: "",
      discussItem: "",
      interestLevel: "",
      note: "",
      listStatus: "未撥打",
      assignedSales: "",
      assignedRegion: "",
      discussNote: "",
      companyName: "匯思雲端股份有限公司",
      contactName: "許雅婷",
      contactDepartment: "資訊部",
      contactTitle: "專案主任",
      contactEmail: "yating.hsu@horizoncloud.tw",
      companyPhone: "02-2626-8899",
      mobilePhone: "",
      contactAddress: "新北市淡水區中正東路 120 號",
      customerData1: "",
      customerData2: "",
      customerData3: "",
      customerData4: "",
    },
  ],

  phoneSalesCustomers: [
    {
      id: 1,
      companyName: "星光資訊股份有限公司",
      unifiedNumber: "24567890",
      industry: "資訊服務",
      companyAddress: "台北市內湖區瑞光路88號",
      companyPhone: "02-2790-1234",
      companyWebsite: "https://starlight.example.com",
      atomPhoneSalesCustomerStatus: 1,
      atomPhoneSalesCustomerValue: 2,
      atomPhoneSalesDataSource: 1,
      isExistingCustomer: false,
      remark: "對雲端方案有興趣",
      customOrder: 1,
      contacterList: [
        {
          id: 11,
          contacterName: "王小明",
          contacterJobTitle: "經理",
          contacterPhone: "0912-111-222",
          contacterEmail: "xiaoming@starlight.example.com",
          contacterLineID: "starlight_wang",
          isPrimary: true,
        },
      ],
    },
    {
      id: 2,
      companyName: "宏達系統科技",
      unifiedNumber: "35678901",
      industry: "製造業",
      companyAddress: "新竹市東區光復路二段200號",
      companyPhone: "03-567-8901",
      companyWebsite: "https://hongda.example.com",
      atomPhoneSalesCustomerStatus: 2,
      atomPhoneSalesCustomerValue: 1,
      atomPhoneSalesDataSource: 2,
      isExistingCustomer: true,
      remark: "已有 PoC 需求",
      customOrder: 2,
      contacterList: [
        {
          id: 21,
          contacterName: "李雅婷",
          contacterJobTitle: "副理",
          contacterPhone: "0922-222-333",
          contacterEmail: "yating@hongda.example.com",
          contacterLineID: "hongda_li",
          isPrimary: true,
        },
      ],
    },
    {
      id: 3,
      companyName: "遠景行銷顧問",
      unifiedNumber: "46789012",
      industry: "行銷顧問",
      companyAddress: "台中市西屯區市政北二路6號",
      companyPhone: "04-2350-5678",
      companyWebsite: "https://vision.example.com",
      atomPhoneSalesCustomerStatus: 3,
      atomPhoneSalesCustomerValue: 2,
      atomPhoneSalesDataSource: 1,
      isExistingCustomer: false,
      remark: "對活動追蹤有需求",
      customOrder: 3,
      contacterList: [
        {
          id: 31,
          contacterName: "張志強",
          contacterJobTitle: "主任",
          contacterPhone: "0933-333-444",
          contacterEmail: "zhichang@vision.example.com",
          contacterLineID: "vision_chang",
          isPrimary: true,
        },
      ],
    },
    {
      id: 4,
      companyName: "智匯金融顧問",
      unifiedNumber: "57890123",
      industry: "金融服務",
      companyAddress: "台北市信義區松仁路100號",
      companyPhone: "02-8100-9988",
      companyWebsite: "https://finwise.example.com",
      atomPhoneSalesCustomerStatus: 4,
      atomPhoneSalesCustomerValue: 1,
      atomPhoneSalesDataSource: 3,
      isExistingCustomer: true,
      remark: "關注資安稽核",
      customOrder: 4,
      contacterList: [
        {
          id: 41,
          contacterName: "陳美玲",
          contacterJobTitle: "總監",
          contacterPhone: "0955-444-555",
          contacterEmail: "meiling@finwise.example.com",
          contacterLineID: "finwise_mei",
          isPrimary: true,
        },
      ],
    },
    {
      id: 5,
      companyName: "綠能科技有限公司",
      unifiedNumber: "68901234",
      industry: "能源",
      companyAddress: "高雄市前鎮區中山二路88號",
      companyPhone: "07-335-8899",
      companyWebsite: "https://greenpower.example.com",
      atomPhoneSalesCustomerStatus: 1,
      atomPhoneSalesCustomerValue: 3,
      atomPhoneSalesDataSource: 2,
      isExistingCustomer: false,
      remark: "需安排示範",
      customOrder: 5,
      contacterList: [
        {
          id: 51,
          contacterName: "吳建國",
          contacterJobTitle: "經理",
          contacterPhone: "0966-555-666",
          contacterEmail: "jianguo@greenpower.example.com",
          contacterLineID: "greenpower_wu",
          isPrimary: true,
        },
      ],
    },
    {
      id: 6,
      companyName: "創新醫療科技",
      unifiedNumber: "79012345",
      industry: "醫療",
      companyAddress: "台北市中正區仁愛路50號",
      companyPhone: "02-2399-1122",
      companyWebsite: "https://medtech.example.com",
      atomPhoneSalesCustomerStatus: 2,
      atomPhoneSalesCustomerValue: 2,
      atomPhoneSalesDataSource: 1,
      isExistingCustomer: true,
      remark: "需要整合既有系統",
      customOrder: 6,
      contacterList: [
        {
          id: 61,
          contacterName: "周婉如",
          contacterJobTitle: "副理",
          contacterPhone: "0977-666-777",
          contacterEmail: "wanru@medtech.example.com",
          contacterLineID: "medtech_zhou",
          isPrimary: true,
        },
      ],
    },
    {
      id: 7,
      companyName: "超點物流股份有限公司",
      unifiedNumber: "80123456",
      industry: "物流",
      companyAddress: "桃園市龜山區科技一路66號",
      companyPhone: "03-355-7788",
      companyWebsite: "https://fastlog.example.com",
      atomPhoneSalesCustomerStatus: 3,
      atomPhoneSalesCustomerValue: 4,
      atomPhoneSalesDataSource: 3,
      isExistingCustomer: false,
      remark: "先提供報價單",
      customOrder: 7,
      contacterList: [
        {
          id: 71,
          contacterName: "徐文彥",
          contacterJobTitle: "主任",
          contacterPhone: "0988-777-888",
          contacterEmail: "wenyan@fastlog.example.com",
          contacterLineID: "fastlog_xu",
          isPrimary: true,
        },
      ],
    },
    {
      id: 8,
      companyName: "翔宇教育科技",
      unifiedNumber: "91234567",
      industry: "教育",
      companyAddress: "台南市東區大學路1號",
      companyPhone: "06-275-1122",
      companyWebsite: "https://skylab.example.com",
      atomPhoneSalesCustomerStatus: 4,
      atomPhoneSalesCustomerValue: 2,
      atomPhoneSalesDataSource: 2,
      isExistingCustomer: true,
      remark: "需求確認中",
      customOrder: 8,
      contacterList: [
        {
          id: 81,
          contacterName: "林淑芬",
          contacterJobTitle: "經理",
          contacterPhone: "0911-888-999",
          contacterEmail: "shufen@skylab.example.com",
          contacterLineID: "skylab_lin",
          isPrimary: true,
        },
      ],
    },
    {
      id: 9,
      companyName: "宏景資安顧問",
      unifiedNumber: "02345678",
      industry: "資安顧問",
      companyAddress: "台北市大安區復興南路10號",
      companyPhone: "02-2700-9988",
      companyWebsite: "https://securewise.example.com",
      atomPhoneSalesCustomerStatus: 5,
      atomPhoneSalesCustomerValue: 3,
      atomPhoneSalesDataSource: 1,
      isExistingCustomer: false,
      remark: "暫停追蹤",
      customOrder: 9,
      contacterList: [
        {
          id: 91,
          contacterName: "黃俊傑",
          contacterJobTitle: "顧問",
          contacterPhone: "0922-999-000",
          contacterEmail: "junjie@securewise.example.com",
          contacterLineID: "securewise_huang",
          isPrimary: true,
        },
      ],
    },
    {
      id: 10,
      companyName: "新創雲端服務",
      unifiedNumber: "13456789",
      industry: "雲端服務",
      companyAddress: "台北市松山區民生東路120號",
      companyPhone: "02-2710-5566",
      companyWebsite: "https://cloudspark.example.com",
      atomPhoneSalesCustomerStatus: 1,
      atomPhoneSalesCustomerValue: 1,
      atomPhoneSalesDataSource: 2,
      isExistingCustomer: false,
      remark: "安排初次會議",
      customOrder: 10,
      contacterList: [
        {
          id: 101,
          contacterName: "周大華",
          contacterJobTitle: "經理",
          contacterPhone: "0933-000-111",
          contacterEmail: "dahua@cloudspark.example.com",
          contacterLineID: "cloudspark_zhou",
          isPrimary: true,
        },
      ],
    },
  ],
  workJobs: [
    {
      id: 1,
      projectName: "企業 CRM 重構",
      stoneName: "需求訪談",
      jobName: "訪談流程整理",
      status: 2,
      startTime: "2026-01-05",
      endTime: "2026-01-12",
      estimatedHours: 16,
      executors: ["王小明", "李雅婷"],
    },
    {
      id: 2,
      projectName: "資安維運平台",
      stoneName: "系統設計",
      jobName: "架構設計",
      status: 2,
      startTime: "2026-02-03",
      endTime: "2026-02-20",
      estimatedHours: 24,
      executors: ["陳志強"],
    },
    {
      id: 3,
      projectName: "資料治理導入",
      stoneName: "資料盤點",
      jobName: "資料分類",
      status: 3,
      startTime: "2026-03-12",
      endTime: "2026-03-25",
      estimatedHours: 18,
      executors: ["張文彥"],
    },
    {
      id: 4,
      projectName: "ERP 整合計畫",
      stoneName: "介面規劃",
      jobName: "API 盤點",
      status: 2,
      startTime: "2026-04-05",
      endTime: "2026-04-18",
      estimatedHours: 20,
      executors: ["吳建國", "林淑芬"],
    },
    {
      id: 5,
      projectName: "雲端遷移專案",
      stoneName: "雲端架構",
      jobName: "雲端資源規劃",
      status: 1,
      startTime: "2026-05-15",
      endTime: "2026-05-28",
      estimatedHours: 14,
      executors: ["黃俊傑"],
    },
    {
      id: 6,
      projectName: "製造數據平台",
      stoneName: "資料串接",
      jobName: "設備資料匯入",
      status: 2,
      startTime: "2026-01-25",
      endTime: "2026-02-08",
      estimatedHours: 22,
      executors: ["周雅婷"],
    },
    {
      id: 7,
      projectName: "IoT 監控系統",
      stoneName: "前端設計",
      jobName: "看板 UI",
      status: 3,
      startTime: "2026-02-25",
      endTime: "2026-03-10",
      estimatedHours: 12,
      executors: ["徐婉如"],
    },
    {
      id: 8,
      projectName: "客服系統升級",
      stoneName: "流程優化",
      jobName: "SOP 更新",
      status: 2,
      startTime: "2026-03-08",
      endTime: "2026-03-18",
      estimatedHours: 10,
      executors: ["王小明"],
    },
    {
      id: 9,
      projectName: "內控稽核系統",
      stoneName: "驗收測試",
      jobName: "UAT 測試",
      status: 4,
      startTime: "2026-06-01",
      endTime: "2026-06-20",
      estimatedHours: 28,
      executors: ["李雅婷", "陳志強"],
    },
    {
      id: 10,
      projectName: "AI 客服導入",
      stoneName: "資料訓練",
      jobName: "語料整理",
      status: 2,
      startTime: "2026-05-01",
      endTime: "2026-05-15",
      estimatedHours: 16,
      executors: ["張文彥"],
    },
  ],
  workJobRecords: [
    {
      id: 101,
      jobId: 1,
      projectName: "企業 CRM 重構",
      stoneName: "需求訪談",
      jobName: "訪談流程整理",
      employeeName: "王小明",
      startTime: "2026-01-06T09:00:00",
      endTime: "2026-01-06T12:00:00",
      remark: "完成訪談提綱與問題清單整理。",
      workMode: "OnSite",
    },
    {
      id: 102,
      jobId: 2,
      projectName: "資安維運平台",
      stoneName: "系統設計",
      jobName: "架構設計",
      employeeName: "陳志強",
      startTime: "2026-02-05T13:30:00",
      endTime: "2026-02-05T16:30:00",
      remark: "完成核心架構圖與模組分工。",
      workMode: "OffSite",
    },
    {
      id: 103,
      jobId: 3,
      projectName: "資料治理導入",
      stoneName: "資料盤點",
      jobName: "資料分類",
      employeeName: "張文彥",
      startTime: "2026-03-14T10:00:00",
      endTime: "2026-03-14T15:00:00",
      remark: "完成資料分類規則與樣本。",
      workMode: "OnSite",
    },
    {
      id: 104,
      jobId: 4,
      projectName: "ERP 整合計畫",
      stoneName: "介面規劃",
      jobName: "API 盤點",
      employeeName: "吳建國",
      startTime: "2026-04-08T09:30:00",
      endTime: "2026-04-08T12:00:00",
      remark: "整理既有 API 清單與依賴項。",
      workMode: "OffSite",
    },
    {
      id: 105,
      jobId: 5,
      projectName: "雲端遷移專案",
      stoneName: "雲端架構",
      jobName: "雲端資源規劃",
      employeeName: "黃俊傑",
      startTime: "2026-05-18T14:00:00",
      endTime: "2026-05-18T17:00:00",
      remark: "完成資源容量與成本估算。",
      workMode: "OnSite",
    },
  ],
};

export function getPaginatedData<T>(
  dataArray: T[],
  pageIndex: number = 0,
  pageSize: number = 10
): { items: T[]; totalCount: number } {
  const startIndex = pageIndex * pageSize;
  const endIndex = startIndex + pageSize;
  return {
    items: dataArray.slice(startIndex, endIndex),
    totalCount: dataArray.length,
  };
}

export function filterData<T extends Record<string, any>>(
  dataArray: T[],
  filters: Partial<T>
): T[] {
  return dataArray.filter((item) => {
    return Object.entries(filters).every(([key, value]) => {
      if (value === null || value === undefined || value === "") {
        return true;
      }
      const itemValue = item[key];
      if (typeof itemValue === "string" && typeof value === "string") {
        return itemValue.toLowerCase().includes(value.toLowerCase());
      }
      return itemValue === value;
    });
  });
}
